apiVersion: v1
kind: Pod
metadata:
  name: communication-pod
  labels:
    name: communication-pod
    app: tacos-app

spec:
  containers:
  - name: communication
    image: segov/comms-notification-service
    imagePullPolicy: "Always"
    ports:
    - containerPort: 3001
