apiVersion: v1
kind: Service
metadata:
  name: communication-service
  labels:
    name: communication-service
    app: tacos-app

spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    name: communication-pod
    app: tacos-app
