apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    name: database-service
    app: tacos-app

spec:
  type: LoadBalancer
  ports:
  - port: 3002
    targetPort: 3002
  selector:
    name: database-pod
    app: tacos-app
