apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    name: notification-service
    app: tacos-app

spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    name: notification-pod
    app: tacos-app
