apiVersion: v1
kind: Pod
metadata:
  name: notification-pod
  labels:
    name: notification-pod
    app: tacos-app

spec:
  containers:
  - name: notification
    image: segov/notification-service
    ports:
    - containerPort: 3000
