apiVersion: v1
kind: Service
metadata:
  name: observability-service
  labels:
    name: observability-service
    app: tacos-app

spec:
  type: LoadBalancer
  ports:
  - port: 3003
    targetPort: 3003
  selector:
    name: observability-pod
    app: tacos-app
