apiVersion: v1
kind: Pod
metadata:
  name: observability-pod
  labels:
    name: observability-pod
    app: tacos-app

spec:
  containers:
  - name: observability
    image: segov/observability-service:latest
    imagePullPolicy: "Always"
    ports:
    - containerPort: 3003
